version: '3.8'
services:
  rpi-images:
    build: .
    image: images-builder:1.0.1
    cap_add:
    - SYS_ADMIN
    container_name: rpi-images
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    hostname: rpi-images
    network_mode: bridge
    privileged: true
    tmpfs:
    - /tmp
    - /run
    - /run/lock
    volumes:
    - /dev:/dev
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
