#!/bin/bash

echo "Build hook running..."

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(git rev-parse --short HEAD)
VCS_URL=$(git config --get remote.origin.url)

echo "BUILD_DATE: ${BUILD_DATE}"
echo "VCS_REF: ${VCS_REF}"
echo "VCS_URL: ${VCS_URL}"

printenv

docker build \
  --build-arg BUILD_DATE="${BUILD_DATE}" \
  --build-arg VCS_REF="${VCS_REF}" \
  --build-arg VCS_URL="${VCS_URL}" \
  -t "$IMAGE_NAME" .
